title: "Buttons"
description: |
  Buttons should be used for dramatic impact and to make things more obvious when an action is required.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button.
    width: "12em"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners.
    background: "--color-secondary"
