title: "Banners"
description:
  Banners is used for some top of homepage.

patterns:
  homepage:
    title: "Homepage"
    description:
      This banner is used for homepage. It is located on top of homepage.
    fields:
      - name: heading
        type: string
        example: "Flowers for every occacion"
      - name: text
        type: string
        example: "Free Delivery"
